services:
  nextjs:
    image: ghcr.io/mrsterdy/dobrenok-landing:latest
    container_name: dobrenok_nextjs_prod
    restart: unless-stopped
    ports:
      - "3000:3000"  # Открываем порт для доступа из Laravel Nginx
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    networks:
      - dobrenok_network  # Используем сеть Laravel проекта

networks:
  dobrenok_network:
    external: true  # Подключаемся к существующей сети Laravel
