import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="antialiased">
        <ReactLenis root>
          <main className="min-h-screen flex flex-col">
            <Header />
            {children}
            <Footer />
          </main>
        </ReactLenis>
        <Toaster />
      </body>
    </html>
  );
}
